//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

import 'package:aryeo/api.dart';
import 'package:test/test.dart';

// tests for PaginationMeta
void main() {
  final instance = PaginationMeta();

  group('test PaginationMeta', () {
    // Total number of records.
    // int total
    test('to test the property `total`', () async {
      // TODO
    });

    // Number of records per page.
    // int perPage
    test('to test the property `perPage`', () async {
      // TODO
    });

    // The current page.
    // int currentPage
    test('to test the property `currentPage`', () async {
      // TODO
    });

    // The last page of records.
    // int lastPage
    test('to test the property `lastPage`', () async {
      // TODO
    });

    // The ID of the first record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
    // int from
    test('to test the property `from`', () async {
      // TODO
    });

    // The ID of the last record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
    // int to
    test('to test the property `to`', () async {
      // TODO
    });

    // The current paged path.
    // String path
    test('to test the property `path`', () async {
      // TODO
    });


  });

}
