//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

import 'package:aryeo/api.dart';
import 'package:test/test.dart';

// tests for PaginationLinks
void main() {
  final instance = PaginationLinks();

  group('test PaginationLinks', () {
    // The first page.
    // String first
    test('to test the property `first`', () async {
      // TODO
    });

    // The last page.
    // String last
    test('to test the property `last`', () async {
      // TODO
    });

    // The previous page. This is specified as either `string` or `null` purely for contract testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
    // String prev
    test('to test the property `prev`', () async {
      // TODO
    });

    // The next page. This is specified as either `string` or `null` purely for contract testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
    // String next
    test('to test the property `next`', () async {
      // TODO
    });


  });

}
