//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class Order {
  /// Returns a new [Order] instance.
  Order({
    @required this.id,
    @required this.number,
    @required this.title,
    @required this.fulfillmentStatus,
    @required this.paymentStatus,
    this.currency,
    this.totalAmount,
    this.paymentUrl,
    this.statusUrl,
    this.address,
    this.customer,
    this.listing,
    this.items = const [],
    this.appointments = const [],
    this.unconfirmedAppointments = const [],
  });

  /// ID of the order. UUID Version 4.
  String id;

  /// A vanity id used for internal tracking of orders for a given vendor.
  int number;

  /// The title of the order, generated by combining the order's number property with the prefix \"Order #\".
  String title;

  /// The fulfillment status of the order.
  OrderFulfillmentStatusEnum fulfillmentStatus;

  /// The payment status of the order.
  OrderPaymentStatusEnum paymentStatus;

  /// The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo.
  OrderCurrencyEnum currency;

  /// A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the total order amount that was or will be charged. This accounts for order items and taxes. 
  // minimum: 0
  int totalAmount;

  /// A URL of a publicly-accessible webpage to pay for the order.
  String paymentUrl;

  /// A URL of a publicly-accessible webpage to see the order's status.
  String statusUrl;

  Address address;

  Group customer;

  Listing listing;

  /// items
  List<OrderItem> items;

  List<Appointment> appointments;

  List<UnconfirmedAppointment> unconfirmedAppointments;

  @override
  bool operator ==(Object other) => identical(this, other) || other is Order &&
     other.id == id &&
     other.number == number &&
     other.title == title &&
     other.fulfillmentStatus == fulfillmentStatus &&
     other.paymentStatus == paymentStatus &&
     other.currency == currency &&
     other.totalAmount == totalAmount &&
     other.paymentUrl == paymentUrl &&
     other.statusUrl == statusUrl &&
     other.address == address &&
     other.customer == customer &&
     other.listing == listing &&
     other.items == items &&
     other.appointments == appointments &&
     other.unconfirmedAppointments == unconfirmedAppointments;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (id == null ? 0 : id.hashCode) +
    (number == null ? 0 : number.hashCode) +
    (title == null ? 0 : title.hashCode) +
    (fulfillmentStatus == null ? 0 : fulfillmentStatus.hashCode) +
    (paymentStatus == null ? 0 : paymentStatus.hashCode) +
    (currency == null ? 0 : currency.hashCode) +
    (totalAmount == null ? 0 : totalAmount.hashCode) +
    (paymentUrl == null ? 0 : paymentUrl.hashCode) +
    (statusUrl == null ? 0 : statusUrl.hashCode) +
    (address == null ? 0 : address.hashCode) +
    (customer == null ? 0 : customer.hashCode) +
    (listing == null ? 0 : listing.hashCode) +
    (items == null ? 0 : items.hashCode) +
    (appointments == null ? 0 : appointments.hashCode) +
    (unconfirmedAppointments == null ? 0 : unconfirmedAppointments.hashCode);

  @override
  String toString() => 'Order[id=$id, number=$number, title=$title, fulfillmentStatus=$fulfillmentStatus, paymentStatus=$paymentStatus, currency=$currency, totalAmount=$totalAmount, paymentUrl=$paymentUrl, statusUrl=$statusUrl, address=$address, customer=$customer, listing=$listing, items=$items, appointments=$appointments, unconfirmedAppointments=$unconfirmedAppointments]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'id'] = id;
      json[r'number'] = number;
      json[r'title'] = title;
      json[r'fulfillment_status'] = fulfillmentStatus;
      json[r'payment_status'] = paymentStatus;
    if (currency != null) {
      json[r'currency'] = currency;
    }
    if (totalAmount != null) {
      json[r'total_amount'] = totalAmount;
    }
    if (paymentUrl != null) {
      json[r'payment_url'] = paymentUrl;
    }
      json[r'status_url'] = statusUrl == null ? null : statusUrl;
    if (address != null) {
      json[r'address'] = address;
    }
    if (customer != null) {
      json[r'customer'] = customer;
    }
    if (listing != null) {
      json[r'listing'] = listing;
    }
    if (items != null) {
      json[r'items'] = items;
    }
    if (appointments != null) {
      json[r'appointments'] = appointments;
    }
    if (unconfirmedAppointments != null) {
      json[r'unconfirmed_appointments'] = unconfirmedAppointments;
    }
    return json;
  }

  /// Returns a new [Order] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static Order fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return Order(
        id: mapValueOfType<String>(json, r'id'),
        number: mapValueOfType<int>(json, r'number'),
        title: mapValueOfType<String>(json, r'title'),
        fulfillmentStatus: OrderFulfillmentStatusEnum.fromJson(json[r'fulfillment_status']),
        paymentStatus: OrderPaymentStatusEnum.fromJson(json[r'payment_status']),
        currency: OrderCurrencyEnum.fromJson(json[r'currency']),
        totalAmount: mapValueOfType<int>(json, r'total_amount'),
        paymentUrl: mapValueOfType<String>(json, r'payment_url'),
        statusUrl: mapValueOfType<String>(json, r'status_url'),
        address: Address.fromJson(json[r'address']),
        customer: Group.fromJson(json[r'customer']),
        listing: Listing.fromJson(json[r'listing']),
        items: OrderItem.listFromJson(json[r'items']),
        appointments: Appointment.listFromJson(json[r'appointments']),
        unconfirmedAppointments: UnconfirmedAppointment.listFromJson(json[r'unconfirmed_appointments']),
      );
    }
    return null;
  }

  static List<Order> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(Order.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <Order>[];

  static Map<String, Order> mapFromJson(dynamic json) {
    final map = <String, Order>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = Order.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of Order-objects as value to a dart map
  static Map<String, List<Order>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<Order>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = Order.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

/// The fulfillment status of the order.
class OrderFulfillmentStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const OrderFulfillmentStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value ?? '';

  String toJson() => value;

  static const FULFILLED = OrderFulfillmentStatusEnum._(r'FULFILLED');
  static const UNFULFILLED = OrderFulfillmentStatusEnum._(r'UNFULFILLED');

  /// List of all possible values in this [enum][OrderFulfillmentStatusEnum].
  static const values = <OrderFulfillmentStatusEnum>[
    FULFILLED,
    UNFULFILLED,
  ];

  static OrderFulfillmentStatusEnum fromJson(dynamic value) =>
    OrderFulfillmentStatusEnumTypeTransformer().decode(value);

  static List<OrderFulfillmentStatusEnum> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(OrderFulfillmentStatusEnum.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <OrderFulfillmentStatusEnum>[];
}

/// Transformation class that can [encode] an instance of [OrderFulfillmentStatusEnum] to String,
/// and [decode] dynamic data back to [OrderFulfillmentStatusEnum].
class OrderFulfillmentStatusEnumTypeTransformer {
  factory OrderFulfillmentStatusEnumTypeTransformer() => _instance ??= const OrderFulfillmentStatusEnumTypeTransformer._();

  const OrderFulfillmentStatusEnumTypeTransformer._();

  String encode(OrderFulfillmentStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a OrderFulfillmentStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  OrderFulfillmentStatusEnum decode(dynamic data, {bool allowNull}) {
    if (data != null) {
      switch (data.toString()) {
        case r'FULFILLED': return OrderFulfillmentStatusEnum.FULFILLED;
        case r'UNFULFILLED': return OrderFulfillmentStatusEnum.UNFULFILLED;
        default:
          if (allowNull == false) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [OrderFulfillmentStatusEnumTypeTransformer] instance.
  static OrderFulfillmentStatusEnumTypeTransformer _instance;
}


/// The payment status of the order.
class OrderPaymentStatusEnum {
  /// Instantiate a new enum with the provided [value].
  const OrderPaymentStatusEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value ?? '';

  String toJson() => value;

  static const PAID = OrderPaymentStatusEnum._(r'PAID');
  static const UNPAID = OrderPaymentStatusEnum._(r'UNPAID');

  /// List of all possible values in this [enum][OrderPaymentStatusEnum].
  static const values = <OrderPaymentStatusEnum>[
    PAID,
    UNPAID,
  ];

  static OrderPaymentStatusEnum fromJson(dynamic value) =>
    OrderPaymentStatusEnumTypeTransformer().decode(value);

  static List<OrderPaymentStatusEnum> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(OrderPaymentStatusEnum.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <OrderPaymentStatusEnum>[];
}

/// Transformation class that can [encode] an instance of [OrderPaymentStatusEnum] to String,
/// and [decode] dynamic data back to [OrderPaymentStatusEnum].
class OrderPaymentStatusEnumTypeTransformer {
  factory OrderPaymentStatusEnumTypeTransformer() => _instance ??= const OrderPaymentStatusEnumTypeTransformer._();

  const OrderPaymentStatusEnumTypeTransformer._();

  String encode(OrderPaymentStatusEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a OrderPaymentStatusEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  OrderPaymentStatusEnum decode(dynamic data, {bool allowNull}) {
    if (data != null) {
      switch (data.toString()) {
        case r'PAID': return OrderPaymentStatusEnum.PAID;
        case r'UNPAID': return OrderPaymentStatusEnum.UNPAID;
        default:
          if (allowNull == false) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [OrderPaymentStatusEnumTypeTransformer] instance.
  static OrderPaymentStatusEnumTypeTransformer _instance;
}


/// The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo.
class OrderCurrencyEnum {
  /// Instantiate a new enum with the provided [value].
  const OrderCurrencyEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value ?? '';

  String toJson() => value;

  static const USD = OrderCurrencyEnum._(r'USD');
  static const CAD = OrderCurrencyEnum._(r'CAD');
  static const GBP = OrderCurrencyEnum._(r'GBP');
  static const CHF = OrderCurrencyEnum._(r'CHF');
  static const EUR = OrderCurrencyEnum._(r'EUR');
  static const AUD = OrderCurrencyEnum._(r'AUD');
  static const NZD = OrderCurrencyEnum._(r'NZD');
  static const ZAR = OrderCurrencyEnum._(r'ZAR');

  /// List of all possible values in this [enum][OrderCurrencyEnum].
  static const values = <OrderCurrencyEnum>[
    USD,
    CAD,
    GBP,
    CHF,
    EUR,
    AUD,
    NZD,
    ZAR,
  ];

  static OrderCurrencyEnum fromJson(dynamic value) =>
    OrderCurrencyEnumTypeTransformer().decode(value);

  static List<OrderCurrencyEnum> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(OrderCurrencyEnum.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <OrderCurrencyEnum>[];
}

/// Transformation class that can [encode] an instance of [OrderCurrencyEnum] to String,
/// and [decode] dynamic data back to [OrderCurrencyEnum].
class OrderCurrencyEnumTypeTransformer {
  factory OrderCurrencyEnumTypeTransformer() => _instance ??= const OrderCurrencyEnumTypeTransformer._();

  const OrderCurrencyEnumTypeTransformer._();

  String encode(OrderCurrencyEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a OrderCurrencyEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  OrderCurrencyEnum decode(dynamic data, {bool allowNull}) {
    if (data != null) {
      switch (data.toString()) {
        case r'USD': return OrderCurrencyEnum.USD;
        case r'CAD': return OrderCurrencyEnum.CAD;
        case r'GBP': return OrderCurrencyEnum.GBP;
        case r'CHF': return OrderCurrencyEnum.CHF;
        case r'EUR': return OrderCurrencyEnum.EUR;
        case r'AUD': return OrderCurrencyEnum.AUD;
        case r'NZD': return OrderCurrencyEnum.NZD;
        case r'ZAR': return OrderCurrencyEnum.ZAR;
        default:
          if (allowNull == false) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [OrderCurrencyEnumTypeTransformer] instance.
  static OrderCurrencyEnumTypeTransformer _instance;
}


