//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class PaginationMeta {
  /// Returns a new [PaginationMeta] instance.
  PaginationMeta({
    @required this.total,
    @required this.perPage,
    @required this.currentPage,
    @required this.lastPage,
    this.from,
    this.to,
    @required this.path,
  });

  /// Total number of records.
  int total;

  /// Number of records per page.
  int perPage;

  /// The current page.
  int currentPage;

  /// The last page of records.
  int lastPage;

  /// The ID of the first record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
  int from;

  /// The ID of the last record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
  int to;

  /// The current paged path.
  String path;

  @override
  bool operator ==(Object other) => identical(this, other) || other is PaginationMeta &&
     other.total == total &&
     other.perPage == perPage &&
     other.currentPage == currentPage &&
     other.lastPage == lastPage &&
     other.from == from &&
     other.to == to &&
     other.path == path;

  @override
  int get hashCode =>
  // ignore: unnecessary_parenthesis
    (total == null ? 0 : total.hashCode) +
    (perPage == null ? 0 : perPage.hashCode) +
    (currentPage == null ? 0 : currentPage.hashCode) +
    (lastPage == null ? 0 : lastPage.hashCode) +
    (from == null ? 0 : from.hashCode) +
    (to == null ? 0 : to.hashCode) +
    (path == null ? 0 : path.hashCode);

  @override
  String toString() => 'PaginationMeta[total=$total, perPage=$perPage, currentPage=$currentPage, lastPage=$lastPage, from=$from, to=$to, path=$path]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'total'] = total;
      json[r'per_page'] = perPage;
      json[r'current_page'] = currentPage;
      json[r'last_page'] = lastPage;
    if (from != null) {
      json[r'from'] = from;
    }
    if (to != null) {
      json[r'to'] = to;
    }
      json[r'path'] = path;
    return json;
  }

  /// Returns a new [PaginationMeta] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static PaginationMeta fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();
      return PaginationMeta(
        total: mapValueOfType<int>(json, r'total'),
        perPage: mapValueOfType<int>(json, r'per_page'),
        currentPage: mapValueOfType<int>(json, r'current_page'),
        lastPage: mapValueOfType<int>(json, r'last_page'),
        from: mapValueOfType<int>(json, r'from'),
        to: mapValueOfType<int>(json, r'to'),
        path: mapValueOfType<String>(json, r'path'),
      );
    }
    return null;
  }

  static List<PaginationMeta> listFromJson(dynamic json, {bool emptyIsNull, bool growable,}) =>
    json is List && json.isNotEmpty
      ? json.map(PaginationMeta.fromJson).toList(growable: true == growable)
      : true == emptyIsNull ? null : <PaginationMeta>[];

  static Map<String, PaginationMeta> mapFromJson(dynamic json) {
    final map = <String, PaginationMeta>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) => map[key] = PaginationMeta.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of PaginationMeta-objects as value to a dart map
  static Map<String, List<PaginationMeta>> mapListFromJson(dynamic json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<PaginationMeta>>{};
    if (json is Map && json.isNotEmpty) {
      json
        .cast<String, dynamic>()
        .forEach((key, dynamic value) {
          map[key] = PaginationMeta.listFromJson(
            value,
            emptyIsNull: emptyIsNull,
            growable: growable,
          );
        });
    }
    return map;
  }
}

