//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.0

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class PaginationMeta {
  /// Returns a new [PaginationMeta] instance.
  PaginationMeta({
    @required this.total,
    @required this.perPage,
    @required this.currentPage,
    @required this.lastPage,
    this.from,
    this.to,
    @required this.path,
  });

  /// Total number of records.
  int total;

  /// Number of records per page.
  int perPage;

  /// The current page.
  int currentPage;

  /// The last page of records.
  int lastPage;

  /// The ID of the first record on this page. This is specified as either `integer` or `null` purely for contract testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
  int from;

  /// The ID of the last record on this page. This is specified as either `integer` or `null` purely for contract testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
  int to;

  /// The current paged path.
  String path;

  @override
  bool operator ==(Object other) => identical(this, other) || other is PaginationMeta &&
     other.total == total &&
     other.perPage == perPage &&
     other.currentPage == currentPage &&
     other.lastPage == lastPage &&
     other.from == from &&
     other.to == to &&
     other.path == path;

  @override
  int get hashCode =>
    (total == null ? 0 : total.hashCode) +
    (perPage == null ? 0 : perPage.hashCode) +
    (currentPage == null ? 0 : currentPage.hashCode) +
    (lastPage == null ? 0 : lastPage.hashCode) +
    (from == null ? 0 : from.hashCode) +
    (to == null ? 0 : to.hashCode) +
    (path == null ? 0 : path.hashCode);

  @override
  String toString() => 'PaginationMeta[total=$total, perPage=$perPage, currentPage=$currentPage, lastPage=$lastPage, from=$from, to=$to, path=$path]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'total'] = total;
      json[r'per_page'] = perPage;
      json[r'current_page'] = currentPage;
      json[r'last_page'] = lastPage;
    if (from != null) {
      json[r'from'] = from;
    }
    if (to != null) {
      json[r'to'] = to;
    }
      json[r'path'] = path;
    return json;
  }

  /// Returns a new [PaginationMeta] instance and imports its values from
  /// [json] if it's non-null, null if [json] is null.
  static PaginationMeta fromJson(Map<String, dynamic> json) => json == null
    ? null
    : PaginationMeta(
        total: json[r'total'],
        perPage: json[r'per_page'],
        currentPage: json[r'current_page'],
        lastPage: json[r'last_page'],
        from: json[r'from'],
        to: json[r'to'],
        path: json[r'path'],
    );

  static List<PaginationMeta> listFromJson(List<dynamic> json, {bool emptyIsNull, bool growable,}) =>
    json == null || json.isEmpty
      ? true == emptyIsNull ? null : <PaginationMeta>[]
      : json.map((v) => PaginationMeta.fromJson(v)).toList(growable: true == growable);

  static Map<String, PaginationMeta> mapFromJson(Map<String, dynamic> json) {
    final map = <String, PaginationMeta>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic v) => map[key] = PaginationMeta.fromJson(v));
    }
    return map;
  }

  // maps a json object with a list of PaginationMeta-objects as value to a dart map
  static Map<String, List<PaginationMeta>> mapListFromJson(Map<String, dynamic> json, {bool emptyIsNull, bool growable,}) {
    final map = <String, List<PaginationMeta>>{};
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic v) {
        map[key] = PaginationMeta.listFromJson(v, emptyIsNull: emptyIsNull, growable: growable);
      });
    }
    return map;
  }
}

